// <auto-generated />
// 这个文件由 tools/build-strings.py 从 Resources/Strings.resx 生成,不要手改。
// 改文案请改 Strings.resx,然后重新生成。

using System.Resources;

namespace Exchoribur.App.Resources;

/// <summary>界面文案。正文住在 Resources/Strings.resx。</summary>
internal static class Strings
{
    private static readonly ResourceManager Manager = new("Exchoribur.App.Resources.Strings", typeof(Strings).Assembly);

    public static string AppName => Get(nameof(AppName));
    public static string MainStatusEmpty => Get(nameof(MainStatusEmpty));
    public static string MainWindowTitleFormat => Get(nameof(MainWindowTitleFormat));
    public static string MainWindowTitleModifiedFormat => Get(nameof(MainWindowTitleModifiedFormat));
    public static string MainLabelUndo => Get(nameof(MainLabelUndo));
    public static string MainLabelRedo => Get(nameof(MainLabelRedo));
    public static string MainMenuUndoFormat => Get(nameof(MainMenuUndoFormat));
    public static string MainMenuRedoFormat => Get(nameof(MainMenuRedoFormat));
    public static string MainUndoDoneFormat => Get(nameof(MainUndoDoneFormat));
    public static string MainRedoDoneFormat => Get(nameof(MainRedoDoneFormat));
    public static string MainBlockEditorTitleFormat => Get(nameof(MainBlockEditorTitleFormat));
    public static string MainUpdateAvailableFormat => Get(nameof(MainUpdateAvailableFormat));
    public static string MainUpdateDownloadingFormat => Get(nameof(MainUpdateDownloadingFormat));
    public static string MainUpdateReadyFormat => Get(nameof(MainUpdateReadyFormat));
    public static string MainVideoUnavailableFormat => Get(nameof(MainVideoUnavailableFormat));
    public static string MainVideoOpenFailedFormat => Get(nameof(MainVideoOpenFailedFormat));
    public static string MainVideoLoadedFormat => Get(nameof(MainVideoLoadedFormat));
    public static string MainHintSelectBlockFirst => Get(nameof(MainHintSelectBlockFirst));
    public static string MainHintOpenBlockEditorFirst => Get(nameof(MainHintOpenBlockEditorFirst));
    public static string MainHintSelectFramesFirst => Get(nameof(MainHintSelectFramesFirst));
    public static string MainHintPlayheadOutsideBlock => Get(nameof(MainHintPlayheadOutsideBlock));
    public static string MainHintKeepAtLeastOneFrame => Get(nameof(MainHintKeepAtLeastOneFrame));
    public static string MainPromptRenameBlock => Get(nameof(MainPromptRenameBlock));
    public static string MainActionNewBlock => Get(nameof(MainActionNewBlock));
    public static string MainActionMoveBlocks => Get(nameof(MainActionMoveBlocks));
    public static string MainActionDeleteBlocks => Get(nameof(MainActionDeleteBlocks));
    public static string MainActionRenameBlock => Get(nameof(MainActionRenameBlock));
    public static string MainActionCopyToOtherChannels => Get(nameof(MainActionCopyToOtherChannels));
    public static string MainActionLinkBlocks => Get(nameof(MainActionLinkBlocks));
    public static string MainActionUnlinkBlocks => Get(nameof(MainActionUnlinkBlocks));
    public static string MainActionSetColor => Get(nameof(MainActionSetColor));
    public static string MainActionTakePlayheadColor => Get(nameof(MainActionTakePlayheadColor));
    public static string MainActionInsertFrame => Get(nameof(MainActionInsertFrame));
    public static string MainActionDeleteFrames => Get(nameof(MainActionDeleteFrames));
    public static string MainStatusBlockCreatedFormat => Get(nameof(MainStatusBlockCreatedFormat));
    public static string MainStatusBlocksMovedFormat => Get(nameof(MainStatusBlocksMovedFormat));
    public static string MainStatusBlocksDeletedFormat => Get(nameof(MainStatusBlocksDeletedFormat));
    public static string MainStatusBlockRenamedFormat => Get(nameof(MainStatusBlockRenamedFormat));
    public static string MainStatusCopiedToOtherChannelsFormat => Get(nameof(MainStatusCopiedToOtherChannelsFormat));
    public static string MainStatusLinkRemoved => Get(nameof(MainStatusLinkRemoved));
    public static string MainStatusLinkedFormat => Get(nameof(MainStatusLinkedFormat));
    public static string MainStatusColorPaintedFormat => Get(nameof(MainStatusColorPaintedFormat));
    public static string MainStatusFrameInsertedFormat => Get(nameof(MainStatusFrameInsertedFormat));
    public static string MainStatusFramesDeletedFormat => Get(nameof(MainStatusFramesDeletedFormat));
    public static string TimelineEmptyHint => Get(nameof(TimelineEmptyHint));
    public static string BlockEditorEmptyHint => Get(nameof(BlockEditorEmptyHint));
    public static string ProjectStatusNoProjectToSave => Get(nameof(ProjectStatusNoProjectToSave));
    public static string ProjectStatusNothingToExport => Get(nameof(ProjectStatusNothingToExport));
    public static string ProjectStatusOpenedFormat => Get(nameof(ProjectStatusOpenedFormat));
    public static string ProjectStatusOpenFailedFormat => Get(nameof(ProjectStatusOpenFailedFormat));
    public static string ProjectStatusSavingFormat => Get(nameof(ProjectStatusSavingFormat));
    public static string ProjectStatusSavedFormat => Get(nameof(ProjectStatusSavedFormat));
    public static string ProjectStatusSavedMissingMediaFormat => Get(nameof(ProjectStatusSavedMissingMediaFormat));
    public static string ProjectStatusExportedFormat => Get(nameof(ProjectStatusExportedFormat));
    public static string ProjectStatusExportFailedFormat => Get(nameof(ProjectStatusExportFailedFormat));
    public static string ProjectStatusLoadedEmptyFormat => Get(nameof(ProjectStatusLoadedEmptyFormat));
    public static string ProjectStatusLoadedFormat => Get(nameof(ProjectStatusLoadedFormat));
    public static string ProjectStatusLoadFailedFormat => Get(nameof(ProjectStatusLoadFailedFormat));
    public static string ProjectPromptNewTimeline => Get(nameof(ProjectPromptNewTimeline));
    public static string ProjectSaveProgressMediaFormat => Get(nameof(ProjectSaveProgressMediaFormat));
    public static string ProjectSaveProgressTimelineFormat => Get(nameof(ProjectSaveProgressTimelineFormat));
    public static string ProjectSaveFailureInUse => Get(nameof(ProjectSaveFailureInUse));
    public static string ProjectSaveFailureAccessDenied => Get(nameof(ProjectSaveFailureAccessDenied));
    public static string ProjectSaveFailureDiskFull => Get(nameof(ProjectSaveFailureDiskFull));
    public static string ProjectSaveFailureUnknownFormat => Get(nameof(ProjectSaveFailureUnknownFormat));
    public static string ProjectSaveFailureKnownFormat => Get(nameof(ProjectSaveFailureKnownFormat));
    public static string FileDialogOpenTimeline => Get(nameof(FileDialogOpenTimeline));
    public static string FileTypeTimelineCsv => Get(nameof(FileTypeTimelineCsv));
    public static string FileDialogImportVideo => Get(nameof(FileDialogImportVideo));
    public static string FileTypeVideo => Get(nameof(FileTypeVideo));
    public static string FileDialogOpenProject => Get(nameof(FileDialogOpenProject));
    public static string FileDialogSaveProject => Get(nameof(FileDialogSaveProject));
    public static string FileDialogExportTimeline => Get(nameof(FileDialogExportTimeline));
    public static string FileTypeProject => Get(nameof(FileTypeProject));
    public static string SettingsGroupGeneral => Get(nameof(SettingsGroupGeneral));
    public static string SettingsGroupTimeline => Get(nameof(SettingsGroupTimeline));
    public static string SettingsGroupAudio => Get(nameof(SettingsGroupAudio));
    public static string SettingsGroupExternalDevices => Get(nameof(SettingsGroupExternalDevices));
    public static string SettingsGroupUpdates => Get(nameof(SettingsGroupUpdates));
    public static string SettingsPageInput => Get(nameof(SettingsPageInput));
    public static string SettingsPageStorage => Get(nameof(SettingsPageStorage));
    public static string SettingsPageTimelineEdit => Get(nameof(SettingsPageTimelineEdit));
    public static string SettingsPageBlocks => Get(nameof(SettingsPageBlocks));
    public static string SettingsPageAudioOutput => Get(nameof(SettingsPageAudioOutput));
    public static string SettingsPageSerialPort => Get(nameof(SettingsPageSerialPort));
    public static string SettingsPageUpdates => Get(nameof(SettingsPageUpdates));
    public static string SettingsPageAbout => Get(nameof(SettingsPageAbout));
    public static string SettingsAudioFollowSystemDefault => Get(nameof(SettingsAudioFollowSystemDefault));
    public static string SettingsAudioHintUnavailable => Get(nameof(SettingsAudioHintUnavailable));
    public static string SettingsAudioHintNoDevices => Get(nameof(SettingsAudioHintNoDevices));
    public static string SettingsUndoDepthHintFormat => Get(nameof(SettingsUndoDepthHintFormat));
    public static string SettingsResetButton => Get(nameof(SettingsResetButton));
    public static string SettingsResetButtonConfirm => Get(nameof(SettingsResetButtonConfirm));
    public static string SettingsLicenseName => Get(nameof(SettingsLicenseName));
    public static string UpdateStatusUnsupported => Get(nameof(UpdateStatusUnsupported));
    public static string UpdateStatusIdle => Get(nameof(UpdateStatusIdle));
    public static string UpdateStatusChecking => Get(nameof(UpdateStatusChecking));
    public static string UpdateStatusUpToDate => Get(nameof(UpdateStatusUpToDate));
    public static string UpdateStatusAvailableFormat => Get(nameof(UpdateStatusAvailableFormat));
    public static string UpdateStatusDownloadingFormat => Get(nameof(UpdateStatusDownloadingFormat));
    public static string UpdateStatusReadyFormat => Get(nameof(UpdateStatusReadyFormat));
    public static string UpdateStatusFailedFormat => Get(nameof(UpdateStatusFailedFormat));

    /// <summary>
    /// 取一条文案。真找不到条目时返回键名本身:界面上会出现一个键名,
    /// 比抛异常或显示空白更容易发现。
    /// </summary>
    private static string Get(string key) => Manager.GetString(key) ?? key;
}
